apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dynamic-volume-claim
spec:
  storageClassName: "nfs-storage-class"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
